# -*- coding: utf-8 -*-
"""Atividade4Teste2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgH4tlbE-kZaVyxU7ktQ7Pxg6jcFBX7D
"""

#import das bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

url ="https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"
df = pd.read_csv(url)
df.head()

print("Dimensões:", df.shape)
display(df.info())

display(df.describe().T)
print("Valores ausentes:", int(df.isna().sum().sum()))
print("Linhas duplicadas:", int(df.duplicated().sum()))
print("\nDistribuição da classe:")
display(df["Class"].value_counts().to_frame("quantidade"))
class_share = df["Class"].value_counts(normalize=True).sort_index() * 100
display(class_share.to_frame("percentual"))

ax = sns.countplot(data=df, x="Class")
ax.set_xticklabels(["Normal (0)", "Fraude (1)"])
ax.set_title("Distribuição das classes")
plt.show()

df_model = df.copy()
df_model["LogAmount"] = np.log1p(df_model["Amount"].clip(lower=0))
df_model.head()

x = df_model.drop(columns="Class")
y = df_model["Class"].astype(int)

x.head()

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    RocCurveDisplay,
    PrecisionRecallDisplay,
    roc_curve,
    roc_auc_score,
)

from sklearn.model_selection import train_test_split
RANDOM_STATE = 11
x_train_full, x_test, y_train_full, y_test = train_test_split(
    x, y, test_size=0.20, stratify=y, random_state=RANDOM_STATE
)
x_train, x_valid, y_train, y_valid = train_test_split(
    x_train_full, y_train_full, test_size=0.20,
    stratify=y_train_full, random_state=RANDOM_STATE
)

print(x_test)
print(x_train_full)

models = {
    "Regressão logística": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(
            class_weight="balanced",
            max_iter=2000,
            random_state=RANDOM_STATE
        ))
    ]),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        class_weight="balanced_subsample",
        min_samples_leaf=2,
        n_jobs=-1,
        random_state=RANDOM_STATE
    )
}

fitted_models = {}

for name, model in models.items():
    model.fit(x_train, y_train)
    fitted_models[name] = model

    print("Treinado:", name)

def best_f1_threshold(y_true, probabilities):

    thresholds = np.linspace(0.01, 0.99, 99)

    scores = [
        f1_score(
            y_true,
            probabilities >= t,
            zero_division=0
        )
        for t in thresholds
    ]

    best_idx = int(np.argmax(scores))

    return float(thresholds[best_idx]), float(scores[best_idx])

print("\nTESTE 1: Treinamento dos modelos")

assert len(fitted_models) == 2, "Quantidade inesperada de modelos!"

assert all(
    hasattr(model, "classes_")
    for model in fitted_models.values()
), "Algum modelo não foi treinado corretamente!"

print("PASSOU: os dois modelos foram treinados com sucesso.")

print("\nTESTE 2: Geração de probabilidades")

for name, model in fitted_models.items():

    probabilities = model.predict_proba(x_valid)[:, 1]

    assert len(probabilities) == len(x_valid), \
        "Quantidade de previsões diferente da validação!"

    assert np.all(np.isfinite(probabilities)), \
        "Existem probabilidades inválidas!"

    assert np.all((probabilities >= 0) & (probabilities <= 1)), \
        "Probabilidades fora do intervalo de 0 a 1!"

    print(f"PASSOU: {name} gerou probabilidades válidas.")

sns.set_theme(style="whitegrid")
resultados = {}

for nome, modelo in fitted_models.items():

    print(f"\n{'='*50}")
    print(f"AVALIAÇÃO DO MODELO: {nome}")
    print(f"{'='*50}")

prob_valid = modelo.predict_proba(x_valid)[:, 1]
melhor_limiar, melhor_f1 = best_f1_threshold(y_valid,prob_valid)

y_prob = modelo.predict_proba(x_test)[:, 1]

y_pred = (y_prob >= melhor_limiar).astype(int)

resultados[nome] = {
        "y_prob": y_prob,
        "y_pred": y_pred,
        "threshold": melhor_limiar
    }

print(f"Limiar escolhido: {melhor_limiar:.2f}")
print(f"F1 na validação: {melhor_f1:.4f}")

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

auc = roc_auc_score(y_test, y_prob)

plt.figure(figsize=(8, 5))

plt.plot(
        fpr,
        tpr,
        label=f"ROC Curve (AUC = {auc:.4f})",
        linewidth=2
    )

plt.plot(
        [0, 1],
        [0, 1],
        linestyle="--",
        color="gray",
        label="Classificador aleatório"
    )

plt.title(f"Curva ROC - {nome}")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

print(f"AUC: {auc:.2f}")
